name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - uses: snok/install-poetry@v1
        with:
          version: 1.7.0
      - name: Install LLVM
        run: sudo apt-get update && sudo apt-get install llvm
      - run: poetry install --no-interaction --no-root
      - run: poetry run pytest
